### ISSUE TITLE
add support for expected grokparsefailure in pattern tests

### ISSUE THREAD

**Issue by jxstanford** [gaspaio/logstash-tester#1]
Great project!  Wondering if you would consider supporting negative tests.  Currently this block of code in `test/spec/patterns_spec.rb` causes test failure when a pattern doesn't match, but if you remove that block, you can easily write a test for negative conditions like:

```
{
  "name": "OpenStack source variations",
  "pattern": "OPENSTACK_SOURCE",
  "cases": {
    {
      "in": "****",
      "out": { "tags": ["_grokparsefailure"] }
    }
  ]
}
```

**Comment by gaspaio** [comment]
Thanks for the issue.

Not sure about this. Why would you want to test explicitly for grokparse failures ? Isn't it enough for the test suite to fail whenever there is a parse failure anywhere ?

**Comment by gaspaio** [comment]
On the other hand, if a test case gets a parsefailure, it will fail anyway, so testing explicitly for failure tags is probably redundant.

What is your use case for explicit negative tests ?

**Comment by jxstanford** [comment]
We have some fairly complex patterns to test, and often, things get through that shouldn't.  In order to be precise about what the pattern matches, we like to test both positive and negative cases, as well as add new cases when bugs are found on either side.  By adding those tests, we can avoid regressions when someone enhances the patterns file to match a slightly different scenario.

If you're interested in more opinion on the subject, google "why write negative tests" and see what reasons others might have.

The question of failing the suite when a test fails is related, but probably a general question of the use case.  I like to generally let the suite run through and get a chance to inspect all failures.  Sometimes that helps see commonality in the failing tests, and arrive at a better solution faster.  In other cases (such as CI systems like TravisCI or CircleCI), you might want to fail fast since they may simply be voting on the build.  In that case, you might put a flag on that functionality and select your favorite as the default.  Many testing frameworks implement some form of that.  For example, python's unittest has a `--failfast` flag.

**Comment by jxstanford** [comment]
BTW, I don't write much ruby either, but definitely have an interest in testing logstash.  Happy to collaborate if you have a list of enhancements that you'd like to see in the project.

**Comment by gaspaio** [comment]
You're right. Merged. I just added a negative test to the example pattern cases.

As for the enhancements, I'll open issues when I think of something. Don't hesitate to do the same and/or provide feedback on the open ones.
Thanks.
